package emy.backend.lawapp50.app.contenus.infrastructure.persistance.repository

import emy.backend.lawapp50.app.contenus.infrastructure.persistance.entity.CommentaireResponseContenuEntity
import org.springframework.data.repository.kotlin.CoroutineCrudRepository

interface CommentaireResponseContenuRepository : CoroutineCrudRepository<CommentaireResponseContenuEntity, Long>